version: '3'
services:
  db:
    image: mysql:8.0.23
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8580:8080

  turbo:
    image: feridferecli/turbo
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_CONNECTION_IP=db
      - DB_CONNECTION_USERNAME=root
      - DB_CONNECTION_PASSWORD=root
    depends_on:
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


volumes:
  db-data:
